# Generated by Django 4.1.3 on 2023-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_user_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='image/profile/picha.png', null=True, upload_to='profiles/'),
        ),
    ]
